#define DSON_SO                              1
#define DSON_SUCH                            2
#define DSON_MANY                            3
#define DSON_WOW                             4
#define DSON_EMPTY                           5
#define DSON_YES                             6
#define DSON_NO                              7
#define DSON_LNUM                            8
#define DSON_DNUM                            9
#define DSON_VERY                           10
#define DSON_STR                            11
#define DSON_ALSO                           12
#define DSON_IS                             13
#define DSON_COMMA                          14
